const titles=['Как я сейчас?','Итоги недели','Выгрузка задач','Выбор фокуса','План действий','Проверка плана'];
const descriptions=['Начните с себя. План должен соответствовать вашему ресурсу.','Заметьте то, что получилось. Незавершённое — тоже источник опыта.','Освободите голову. Запишите всё, пока не выбирая приоритеты.','Один главный фокус, две поддерживающие задачи. Остальное может подождать.','Превратите намерение в конкретный первый шаг.','Хороший план оставляет пространство для жизни.'];
const categories=['Здоровье и энергия','Работа и реализация','Отдых и расслабление'];
const defaults=[0,7,7,3,7,0];
const key='weekly-focus-v1';
const fresh=()=>({id:crypto.randomUUID(),date:new Date().toISOString(),step:0,answers:{},tasks:[],timers:defaults.map(m=>({minutes:m,remaining:m*60,end:null})),finished:false});
let state,storageError=false;
try{state=JSON.parse(localStorage.getItem(key));if(!state||!Array.isArray(state.sessions)||!state.sessions.length)state=null;}catch{storageError=true;}
state??={sessions:[fresh()],current:null};state.current??=state.sessions[0].id;
const $=s=>document.querySelector(s);
const current=()=>state.sessions.find(x=>x.id===state.current)||state.sessions[0];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){try{localStorage.setItem(key,JSON.stringify(state));storageError=false;}catch{storageError=true;}$('#save').textContent=storageError?'Не удалось сохранить — экспортируйте записи':'Сохранено на устройстве';$('#save').classList.toggle('error',storageError);}
const date=s=>new Date(s).toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'});
function field(id,label,type='text'){const v=current().answers[id]??'';return `<label for="${id}">${label}</label>${type==='area'?`<textarea id="${id}" data-answer="${id}">${esc(v)}</textarea>`:`<input id="${id}" type="${type}" data-answer="${id}" value="${esc(v)}">`}`;}
function scale(id,label){const v=current().answers[id]??5;return `<label for="${id}">${label} <output id="${id}Value">${v}</output>/10</label><input id="${id}" type="range" min="1" max="10" value="${v}" data-answer="${id}"><div class="scale"><span>1 — низкий уровень</span><span>10 — высокий уровень</span></div>`;}
function remaining(t){return t.end?Math.max(0,Math.ceil((t.end-Date.now())/1000)):t.remaining;}
function timer(){const t=current().timers[current().step];return `<div class="timer"><strong id="clock" aria-live="off"></strong><input aria-label="Длительность в минутах" id="minutes" type="number" min="0" max="180" value="${t.minutes}"><span>мин.</span><button id="toggleTimer">${t.end?'Пауза':'Старт'}</button><button id="addMinute">+1 мин</button><button id="resetTimer">Сброс</button><span id="timerStatus" role="status"></span></div>`;}
function tasks(mode){return current().tasks.map(t=>`<div class="task">${mode==='review'?`<input type="checkbox" aria-label="Выполнено: ${esc(t.text)}" data-done="${t.id}" ${t.done?'checked':''}>`:''}<span>${esc(t.text)}<br><small class="tag">${categories[t.category]}</small></span>${mode==='priority'?`<select aria-label="Приоритет: ${esc(t.text)}" data-priority="${t.id}">${[['later','Не на этой неделе'],['focus','Главный фокус'],['support','Поддержка']].map(([v,l])=>`<option value="${v}" ${t.priority===v?'selected':''}>${l}</option>`).join('')}</select>`:''}<button data-delete="${t.id}" aria-label="Удалить задачу: ${esc(t.text)}">×</button></div>`).join('')||'<p class="intro">Пока нет задач. Добавьте их на этапе выгрузки.</p>';}
function render(){const s=current(),i=s.step;$('#date').textContent=date(s.date);$('#steps').innerHTML=titles.map((t,j)=>`<button data-step="${j}" class="${i===j?'active':''}" ${i===j?'aria-current="step"':''}><b>${j+1}</b>${t}</button>`).join('');let body='';
if(i===0)body=scale('energy','Энергия за последние две недели')+scale('stress','Напряжение за последние две недели')+field('resource','Сколько ресурса у меня реально есть на эту неделю?','area');
if(i===1){const prev=state.sessions.find(x=>x.id!==s.id&&new Date(x.date)<new Date(s.date));body=(prev?`<div class="notice">Предыдущая сессия: ${date(prev.date)} <button id="copyPrevious">Добавить её выбранные задачи для проверки</button></div>`:'')+tasks('review')+field('wins','Что удалось реализовать или сделать?','area')+field('avoid','Что я переносил(а) или избегал(а)? Почему?','area')+field('lesson','Что из этого опыта я учту на следующей неделе?','area');}
if(i===2)body=tasks('plain')+`<form id="addTask" class="add"><input id="taskText" type="text" placeholder="Что хочется или нужно сделать?" aria-label="Новая задача" required maxlength="500"><select id="category" aria-label="Категория">${categories.map((c,j)=>`<option value="${j}">${c}</option>`).join('')}</select><button class="primary">Добавить</button></form><p class="intro">Включите сюда отдых. Не каждую задачу нужно выполнять сейчас.</p>`;
if(i===3)body=tasks('priority')+'<div class="notice" id="priorityNotice">Выберите один главный фокус и до двух поддерживающих задач. Выполненные задачи оставьте без приоритета.</div>';
if(i===4)body=field('focus','Мой главный фокус недели')+'<h3 class="planHeading">К концу недели я выбираю делать:</h3>'+categories.map((c,j)=>field('plan'+j,c,'area')).join('')+field('first','Моё первое действие')+field('when','Когда я его сделаю','datetime-local')+field('not','Чтобы не перегрузить себя, на этой неделе я не буду','area');
if(i===5)body=scale('planStress','Когда смотрю на план, сколько напряжения чувствую?')+scale('realistic','Насколько реалистично выполнить план?')+field('habits','Какие привычки помогут реализовать этот план?','area')+summary(s);
$('#content').innerHTML=`<div class="eyebrow">ЭТАП ${i+1} ИЗ 6</div><h2>${titles[i]}</h2><p class="intro">${descriptions[i]}</p>${timer()}${body}`;$('#back').disabled=i===0;$('#next').textContent=i===5?'Завершить сессию ✓':'Продолжить →';$('#progress').textContent=`${i+1} / 6`;tick();save();}
function summary(s){const a=s.answers;return `<div class="summary"><div class="eyebrow">ВАША НЕДЕЛЯ В ОДНОЙ КАРТОЧКЕ</div><h3>${esc(a.focus||'Фокус пока не выбран')}</h3><p>${a.result?`<b>Результат:</b> ${esc(a.result)}<br>`:''}<b>Первый шаг:</b> ${esc(a.first||'—')}<br><b>Когда:</b> ${esc(a.when?.replace('T',' ')||'—')}</p>${categories.map((c,j)=>`<p><b>${c}</b><br>${esc(a['plan'+j]||'—')}</p>`).join('')}<p><b>Поддерживающие задачи</b><br>${s.tasks.filter(t=>t.priority==='support'&&!t.done).map(t=>'• '+esc(t.text)).join('<br>')||'—'}</p><p><b>На этой неделе я не буду:</b><br>${esc(a.not||'—')}</p></div><div class="exportActions"><button id="export">Экспорт всех записей</button> <button id="print">Печать плана</button></div>`;}
function navigate(i){const s=current();const t=s.timers[s.step];t.remaining=remaining(t);t.end=null;s.step=i;if(i===4)categories.forEach((c,j)=>{if(s.answers['plan'+j]===undefined)s.answers['plan'+j]=s.tasks.filter(t=>t.category===j&&t.priority!=='later'&&!t.done).map(t=>t.text).join('\n');});if(i===4&&!s.answers.focus)s.answers.focus=s.tasks.find(t=>t.priority==='focus'&&!t.done)?.text||'';render();}
function tick(){const s=current(),t=s.timers[s.step],r=remaining(t);if(t.end&&r===0){t.end=null;t.remaining=0;save();try{const C=window.AudioContext||window.webkitAudioContext;const c=new C(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);g.gain.value=.08;o.frequency.value=660;o.start();o.stop(c.currentTime+.4);o.onended=()=>c.close();}catch{}$('#toggleTimer').textContent='Старт';}if($('#clock'))$('#clock').textContent=t.minutes===0?'Без таймера':`${Math.floor(r/60).toString().padStart(2,'0')}:${(r%60).toString().padStart(2,'0')}`;if($('#timerStatus'))$('#timerStatus').textContent=t.minutes>0&&r===0?'Время вышло. Продолжайте в своём темпе.':'';}
document.addEventListener('input',e=>{const id=e.target.dataset.answer;if(id){current().answers[id]=e.target.type==='range'?Number(e.target.value):e.target.value;const out=$(`#${id}Value`);if(out)out.textContent=e.target.value;save();}});
document.addEventListener('change',e=>{const s=current(),el=e.target;if(el.id==='minutes'){const m=Math.max(0,Math.min(180,Number(el.value)||0));Object.assign(s.timers[s.step],{minutes:m,remaining:m*60,end:null});render();}if(el.dataset.done){const t=s.tasks.find(t=>t.id===el.dataset.done);t.done=el.checked;if(t.done)t.priority='later';save();}if(el.dataset.priority){const t=s.tasks.find(t=>t.id===el.dataset.priority),v=el.value;if(t.done&&v!=='later'){el.value=t.priority;$('#priorityNotice').textContent='Эта задача уже выполнена. Выберите задачу на новую неделю.';return;}if(v==='support'&&s.tasks.filter(x=>x.priority==='support'&&x.id!==t.id).length>=2){el.value=t.priority;$('#priorityNotice').textContent='Оставьте максимум две поддерживающие задачи.';return;}if(v==='focus')s.tasks.forEach(x=>{if(x.priority==='focus')x.priority='later';});t.priority=v;render();}});
document.addEventListener('submit',e=>{if(e.target.id!=='addTask')return;e.preventDefault();const text=$('#taskText').value.trim();if(!text)return;current().tasks.push({id:crypto.randomUUID(),text,category:Number($('#category').value),done:false,priority:'later'});render();$('#taskText').focus();});
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='svoya-nedelya-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function downloadTasks(){
const s=current(),a=s.answers;
const lines=['Сессия планирования',date(s.date),'','Мой главный фокус недели',a.focus||'—','','К концу недели я выбираю делать:'];
categories.forEach((c,j)=>{lines.push('',c,a['plan'+j]||'—');const tasks=s.tasks.filter(t=>t.category===j);if(tasks.length){lines.push('Задачи из выгрузки:');tasks.forEach(t=>lines.push(`${t.done?'[✓]':'[ ]'} ${t.text} — ${t.priority==='focus'?'главный фокус':t.priority==='support'?'поддержка':'не на этой неделе'}`));}});
lines.push('','Моё первое действие',a.first||'—','','Когда я его сделаю',a.when?.replace('T',' ')||'—','','На этой неделе я не буду',a.not||'—','','Какие привычки помогут',a.habits||'—');
const blob=new Blob(['\uFEFF'+lines.join('\n')],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='plan-nedeli-'+s.date.slice(0,10)+'.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
function history(){ $('#dialogContent').innerHTML=`<h2>Ваши недели</h2><p class="intro">Открывайте прошлые планы или начните новую сессию.</p><button id="newSession" class="primary">Новая неделя</button>${state.sessions.map(s=>`<div class="historyRow"><span>${date(s.date)} · ${s.finished?'Завершена':'Черновик'}<br>${esc(s.answers.focus||'Фокус ещё не выбран')}</span><div class="historyActions"><button data-open="${s.id}">Открыть</button><button class="danger" data-delete-session="${s.id}" aria-label="Удалить неделю от ${date(s.date)}">Удалить эту неделю</button></div></div>`).join('')}<div class="notice">Резервная копия содержит ваши личные ответы. Храните её у себя.</div><button id="export">Экспорт всех записей</button><label for="import">Восстановить резервную копию (добавит отсутствующие сессии)</label><input id="import" type="file" accept="application/json,.json"><p id="importStatus" role="status"></p><div class="notice">Удаление действует только в этом браузере. Скачанные копии остаются у вас.</div><button id="deleteAll" class="danger">Удалить все записи</button>`;$('#dialog').showModal();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const s=current(),t=s.timers[s.step];if(b.dataset.deleteSession){
const target=state.sessions.find(x=>x.id===b.dataset.deleteSession);
if(!target||!window.confirm('Удалить неделю от '+date(target.date)+'? Все её задачи и ответы будут удалены. Это действие нельзя отменить.'))return;
state.sessions=state.sessions.filter(x=>x.id!==target.id);
if(!state.sessions.length)state.sessions=[fresh()];
if(state.current===target.id)state.current=state.sessions[0].id;
render();history();return;
}
if(b.id==='deleteAll'){
if(!window.confirm('Удалить все недели, задачи и ответы в этом браузере? Это действие нельзя отменить. При необходимости сначала экспортируйте записи.'))return;
const clean=fresh();state={sessions:[clean],current:clean.id};
render();history();return;
}
if(b.dataset.step)navigate(Number(b.dataset.step));if(b.dataset.delete){s.tasks=s.tasks.filter(t=>t.id!==b.dataset.delete);render();}if(b.dataset.open){navigate(s.step);state.current=b.dataset.open;$('#dialog').close();render();}switch(b.id){case 'back':navigate(Math.max(0,s.step-1));break;case 'next':if(s.step<5)navigate(s.step+1);else{s.finished=true;t.remaining=remaining(t);t.end=null;save();$('#dialogContent').innerHTML='<h2>План недели сохранён</h2><p class="intro">Скачайте задачи, чтобы ваш план был под рукой.</p>'+summary(s)+'<button id="downloadTasks" class="primary">Скачать задачи</button><p id="goodbye" role="status"></p>';$('#dialog').showModal();}break;case 'toggleTimer':if(t.minutes===0)return;if(t.end){t.remaining=remaining(t);t.end=null;}else{if(t.remaining===0)t.remaining=t.minutes*60;t.end=Date.now()+t.remaining*1000;}save();b.textContent=t.end?'Пауза':'Старт';tick();break;case 'addMinute':t.remaining=remaining(t)+60;t.minutes=t.minutes||1;if(t.end)t.end=Date.now()+t.remaining*1000;save();tick();break;case 'resetTimer':t.end=null;t.remaining=t.minutes*60;render();break;case 'history':history();break;case 'closeDialog':$('#dialog').close();break;case 'export':exportData();break;case 'downloadTasks':downloadTasks();$('#goodbye').textContent='Увидимся на следующей неделе';break;case 'print':window.print();break;case 'newSession':navigate(s.step);const n=fresh();state.sessions.unshift(n);state.current=n.id;$('#dialog').close();render();break;case 'copyPrevious':const prev=state.sessions.find(x=>x.id!==s.id&&new Date(x.date)<new Date(s.date));prev?.tasks.filter(x=>x.priority!=='later').forEach(x=>{if(!s.tasks.some(y=>y.source===x.id))s.tasks.push({...x,id:crypto.randomUUID(),source:x.id,priority:'later'});});render();break;}});
document.addEventListener('change',async e=>{if(e.target.id!=='import')return;try{const file=e.target.files[0];if(!file)return;if(file.size>5000000)throw Error();const data=JSON.parse(await file.text());if(!Array.isArray(data.sessions)||!data.sessions.length)throw Error();for(const s of data.sessions){if(typeof s.id!=='string'||!Number.isFinite(Date.parse(s.date))||!Number.isInteger(s.step)||s.step<0||s.step>5||!s.answers||typeof s.answers!=='object'||!Array.isArray(s.tasks)||!Array.isArray(s.timers)||s.timers.length!==6)throw Error();if(!Object.values(s.answers).every(x=>typeof x==='string'||typeof x==='number'))throw Error();if(!s.tasks.every(t=>typeof t.id==='string'&&typeof t.text==='string'&&Number.isInteger(t.category)&&t.category>=0&&t.category<3&&['later','focus','support'].includes(t.priority)))throw Error();if(!s.timers.every(t=>Number.isFinite(t.minutes)&&t.minutes>=0&&t.minutes<=180&&Number.isFinite(t.remaining)&&t.remaining>=0))throw Error();}for(const s of data.sessions){if(!state.sessions.some(x=>x.id===s.id)){s.timers.forEach(t=>t.end=null);state.sessions.push(s);}}state.sessions.sort((a,b)=>new Date(b.date)-new Date(a.date));save();$('#importStatus').textContent='Записи восстановлены. Откройте историю заново, чтобы увидеть их.';}catch{$('#importStatus').textContent='Не удалось прочитать копию. Выберите файл экспорта этого приложения.'}});
setInterval(tick,250);render();
